#file: noinspection SpringBootApplicationYaml


# actuator configuration
management:
  endpoints:
    web:
      exposure:
        include:
          - env

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: ${dbuser}
    password: ${dbpassword}
  jpa:
    hibernate:
      ddl-auto: create
  #  AWS configuration
  cloud:
    aws:
      secretsmanager:
        region: us-east-1
        endpoint: http://localhost:4566
      credentials:
        access-key: none
        secret-key: none

    credentials:
      profile:
        name: personal

  config:
    import:
      - aws-secretsmanager:/secret/db-mysql-credential
#      - optional:aws-secretsmanager:/secrets/optional-secret
server:
  port: 8787
